Fix random bug where regex doesn’t match every reg. expression
taskrabbit/react-native-parsed-text pull request #47
Opened 2018-05-16 15:21 UTC by christophby

Im my case it skipped random matches. This PR fixes it.

2018-08-15 18:52 UTC, scottmas approved these changes
I too faced this same annoying error and came upon the same fix, since RegExp.exec mutates the RegExp object

2018-08-15 18:57 UTC, scottmas commented
In the meanwhile, while people are waiting for a fix, you can simply always ensure the pattern is a fresh instance in your render method. 
```javascript
const HASHTAG_REGEX = /#[a-z]+\b/i
...
pattern: new RegExp(HASHTAG_REGEX)
```

2018-08-15 19:05 UTC, scottmas commented on src/lib/TextExtraction.js
> +          let matches = new RegExp(pattern.pattern).exec(textLeft);
Would be _slightly_ more efficient to only clone it once outside the while loop...

2018-11-15 22:10 UTC, fbartho commented
@christophby & @scottmas I'd be happy to ship this if the suggested change was made, and if we add tests that exercise this bug, so we make sure not to have a regression.

Please merge in master before you do that as I've switched the test harness to jest. 🥂

2018-11-15 22:11 UTC, fbartho requested changes
Please apply: 
https://github.com/taskrabbit/react-native-parsed-text/pull/47/files#r210374952

And please add tests!

2019-08-22 12:17 UTC, shramadani approved these changes

2019-08-22 12:19 UTC, shramadani commented
> Please apply:
> https://github.com/taskrabbit/react-native-parsed-text/pull/47/files#r210374952
> 
> And please add tests!

Just tried this change locally and seems to be working as expected. Is it possible to merge this PR please?

2019-11-18 22:01 UTC, fbartho commented
@shramadani -- if you want to help contribute tests for this PR, I'm looking to ship a new release of this this week. Please let me know if you're interested!

2019-12-05 17:03 UTC, ouoru commented
@fbartho any updates on this? 😃

2020-06-10 22:52 UTC, fbartho commented
Since there are no current tests, I'm going to try to write some myself. Additionally, there was a comment that I requested get applied, and that was resolved instead of applying it.

I probably will reset the regexp by setting `.lastIndex = 0` before the while loop assuming that doesn't break things.

This means I'm probably not going to merge this PR as is. I hope you understand @christophby

2020-06-11 00:18 UTC, fbartho commented
There is an alternative implementation in this commit: https://github.com/taskrabbit/react-native-parsed-text/commit/e8f140e170a71c85e4358dcd9f64d593c10ad9fd

I will spin a beta build shortly

2020-06-11 01:05 UTC, fbartho commented
`react-native-parsed-text@0.0.22-beta.1` is now available on npm -- please let me know if you have any issues!

2020-07-07 04:20 UTC, fbartho commented
Closing this PR as there would now be conflicts, but please report if you have any issues with the current implementation, or if further fixes are necessary!

2020-07-07 04:20 UTC, closed without merging